### ISSUE TITLE
I need built .so filea

### ISSUE THREAD

**Issue by hamedali1336** [atsushieno/libcxx-provider#1]
Can you please provide me with already built .so files with ndk version 25.1.8937393 ? Thanks in advance

**Comment by atsushieno** [comment]
Not by myself, but once you set up NDK 25.1 you should already have four `libc++_shared.so` files locally, at: `$(ANDROID_SDK_ROOT)/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/{ABI}/` (where `{ABI}` is one of `aarch64-linux-android`, `i686-linux-android`, `arm-linux-androideabi` or `x86_64-linux-android`).
